CREATE TABLE public.users(
	id INT GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
	email CHARACTER VARYING (320) NOT NULL,
	password CHARACTER VARYING (25) NOT NULL,
	CONSTRAINT pk_users PRIMARY KEY(id),
	CONSTRAINT uc_users_email UNIQUE(email)	
);

CREATE TABLE public.employees(
	user_id INT NOT NULL,
	first_name CHARACTER VARYING (35) NOT NULL,
	last_name CHARACTER VARYING (35) NOT NULL,
	CONSTRAINT pk_employees PRIMARY KEY(user_id),
	CONSTRAINT fk_employees_users FOREIGN KEY(user_id) REFERENCES public.users(id)
);

CREATE TABLE public.candidates(
	user_id INT NOT NULL,
	first_name CHARACTER VARYING (35) NOT NULL,
	last_name CHARACTER VARYING (35) NOT NULL,
	identity_number CHARACTER VARYING(11) NOT NULL,
	birth_year INT NOT NULL,
	CONSTRAINT pk_candidates PRIMARY KEY(user_id),
	CONSTRAINT fk_candidates_users FOREIGN KEY(user_id) REFERENCES public.users(id),
	CONSTRAINT uc_candidates_identity_number UNIQUE(identity_number)
);

CREATE TABLE public.employers(
	user_id INT NOT NULL,
	company_name CHARACTER VARYING (255) NOT NULL,
	web_address CHARACTER VARYING (50) NOT NULL,
	phone_number CHARACTER VARYING (12) NOT NULL,
	CONSTRAINT pk_employers PRIMARY KEY(user_id),
	CONSTRAINT fk_employers_users FOREIGN KEY(user_id) REFERENCES public.users(id)
);

CREATE TABLE public.verification_codes(
	id INT GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
	code CHARACTER VARYING (38) NOT NULL,
	is_verified BOOLEAN NOT NULL,
	verified_date DATE,
	CONSTRAINT pk_verification_codes PRIMARY KEY(id),
	CONSTRAINT uc_verification_codes_code UNIQUE (code)
);

CREATE TABLE public.verification_codes_candidates(
	verification_code_id INT NOT NULL,
	candidate_id INT NOT NULL,
	CONSTRAINT pk_verification_codes_candidates PRIMARY KEY(verification_code_id),
	CONSTRAINT fk_verification_codes_candidates_verification_codes FOREIGN KEY(verification_code_id) REFERENCES public.verification_codes(id),
	CONSTRAINT fk_verification_codes_candidates_candidates FOREIGN KEY(candidate_id) REFERENCES public.candidates(user_id)
);

CREATE TABLE public.verification_codes_employers(
	verification_code_id INT NOT NULL,
	employer_id INT NOT NULL,
	CONSTRAINT pk_verification_codes_employers PRIMARY KEY(verification_code_id),
	CONSTRAINT fk_verification_codes_employers_verification_codes FOREIGN KEY(verification_code_id) REFERENCES public.verification_codes(id),
	CONSTRAINT fk_verification_codes_employers_employers FOREIGN KEY(employer_id) REFERENCES public.employers(user_id)
);

CREATE TABLE public.employee_confirms(
	id INT GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
	employee_id INT NOT NULL,
	is_confirmed BOOLEAN NOT NULL,
	confirm_date DATE,
	CONSTRAINT pk_employee_confirms PRIMARY KEY(id),
	CONSTRAINT fk_employee_confirms_employee_id FOREIGN KEY(employee_id) REFERENCES public.employers(user_id)
);

CREATE TABLE public.employee_confirm_employers(
	employee_confirm_id INT NOT NULL,
	employer_id INT NOT NULL,
	CONSTRAINT pk_employee_confirm_employers PRIMARY KEY(employee_confirm_id),
	CONSTRAINT fk_employee_confirm_employers_employee_confirms FOREIGN KEY(employee_confirm_id) REFERENCES public.employee_confirms(id),
	CONSTRAINT fk_employee_confirm_employers_employers FOREIGN KEY(employer_id) REFERENCES public.employers(user_id)
);

CREATE TABLE public.job_positions(
	id INT GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
	position CHARACTER VARYING(255),
	CONSTRAINT pk_job_positions PRIMARY KEY(id),
	CONSTRAINT uc_job_positions_position UNIQUE(position)
);

ALTER TABLE public.users ADD is_active boolean;
ALTER TABLE public.employees ADD is_active boolean;
ALTER TABLE public.employers ADD is_active boolean;
ALTER TABLE public.candidates ADD is_active boolean;
ALTER TABLE public.users
    ADD COLUMN is_deleted boolean NOT NULL;

CREATE TABLE public.cities(
	id INT GENERATED BY DEFAULT AS IDENTITY(INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
	name CHARACTER VARYING(320) NOT NULL,
	CONSTRAINT pk_cities PRIMARY KEY(id)
);

CREATE TABLE public.job_adverts(
	id INT GENERATED BY DEFAULT AS IDENTITY(INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
	employer_id INT NOT NULL,
	job_position_id INT NOT NULL,
	city_id INT NOT NULL,
	job_position CHARACTER VARYING(320) NOT NULL,
	city CHARACTER VARYING(320) NOT NULL,
	max_salary INT,
	min_salary INT,
	vacant_position INT NOT NULL,
	deadline DATE NOT NULL,
	is_active BOOLEAN NOT NULL,
	is_deleted BOOLEAN NOT NULL,
	published_date DATE NOT NULL,
	CONSTRAINT pk_job_adverts PRIMARY KEY(id),
	CONSTRAINT fk_job_adverts_employers FOREIGN KEY(employer_id) REFERENCES public.employers(user_id),
	CONSTRAINT fk_job_adverts_job_positions FOREIGN KEY(job_position_id) REFERENCES public.job_positions(id),
	CONSTRAINT fk_job_adverts_cities FOREIGN KEY(city_id) REFERENCES public.cities(id)
)

ALTER TABLE public.cities
    RENAME name TO city_name;


